name: tp0
networks:
  testing_net:
    ipam:
      config:
        - subnet: 172.25.125.0/24
      driver: default
services:
  client1:
    container_name: client1
    depends_on:
      - server
    entrypoint: /client
    image: client:latest
    networks:
      - testing_net
    volumes:
      - /home/solmoon/distribuidos/tp0-base/client/config.yaml:/config.yaml
      - /home/solmoon/distribuidos/tp0-base/.data:/.data
  server:
    container_name: server
    entrypoint: python3 /main.py
    image: server:latest
    networks:
      - testing_net
    volumes:
      - /home/solmoon/distribuidos/tp0-base/server/config.ini:/config.ini
