name: tp0
networks:
  testing_net:
    ipam:
      config:
        - subnet: 172.25.125.0/24
      driver: default
services:
  client1:
    container_name: client1
    depends_on:
      - server
    entrypoint: /client
    image: client:latest
    environment:
      - CLI_ID=1
      - NOMBRE=Laura
      - APELLIDO=Perez
      - DOCUMENTO=12345678
      - NACIMIENTO=1960-05-28
      - NUMERO=7089
    networks:
      - testing_net
    volumes:
      - /home/solmoon/distribuidos/tp0-base/client/config.yaml:/config.yaml
  server:
    container_name: server
    entrypoint: python3 /main.py
    image: server:latest
    networks:
      - testing_net
    volumes:
      - /home/solmoon/distribuidos/tp0-base/server/config.ini:/config.ini
